---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "marthoc/deconz"
    pull: yes
    state: 'started'
    env:
      "TZ": "{{ timezone }}"
    ports:
      - "4043:443"
      - "8085:80"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/root/.local/share/dresden-elektronik/deCONZ"
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
    restart_policy: unless-stopped