# General variables
#
timezone: Europe/Amsterdam

ntp_timezone: "{{ timezone }}"

username: notthebee

email: moe@notthebe.ee

guid: "1000"

shell: /usr/bin/fish

docker_dir: /opt/docker/data

dotfiles_repo: https://github.com/notthebee/dotfiles

# SSH (geerlingguy.security)

security_ssh_port: 69

security_sudoers_passwordless: [ "{{ username }}" ]

security_autoupdate_reboot: "true"

host: "{{ duckdns_domain }}.duckdns.org"

# Docker
copy_persistent_data: false

force_copy_persistent_data: false

enable_smarthome: true

enable_plex: true

enable_downloaders: true

enable_deluge: true

enable_bitwarden: true

enable_duckdns: true

enable_homer: true

enable_nextcloud: true

enable_swag: true

enable_wireguard: true

# Samba
samba_server_string: "{{ hostname }}"