# General variables
timezone: Europe/Amsterdam

ntp_timezone: "{{ timezone }}"

username: notthebee

ssh_public_key: https://github.com/notthebee.keys

email: moe@notthebe.ee

guid: "1000"

shell: /usr/bin/fish

docker_dir: /opt/docker/data

dotfiles_repo: https://github.com/notthebee/dotfiles


# SSH (geerlingguy.security)
security_ssh_port: 69

security_sudoers_passwordless: [ "{{ username }}" ]

security_autoupdate_reboot: "true"

host: "{{ duckdns_domain }}.duckdns.org"


# Docker
copy_persistent_data: false

force_copy_persistent_data: false

enable_smarthome: true

enable_plex: true

enable_downloaders: true

enable_deluge: true

enable_bitwarden: true

enable_duckdns: true

enable_homer: true

enable_nextcloud: true

enable_swag: true

enable_wireguard: true


# Samba
samba_server_string: "{{ hostname }}"


# Time Machine
timemachine_root: /mnt/timemachine

timemachine_drive: /dev/disk/by-label/TimeMachine

enable_timemachine: true


# Snapraid and MergerFS

mergerfs_root: /mnt/storage

disks:
  - { name: /mnt/data1, src: /dev/disk/by-label/Data1 }
  - { name: /mnt/data2, src: /dev/disk/by-label/Data2 }

parity_disks:
  - { name: /mnt/parity1, src: /dev/disk/by-label/Parity1 }

snapraid_scrub_schedule:
  hour: 1
  weekday: 3