---
- name: Install required system packages
  apt: 
    name:
      - netatalk
      - hfsplus
      - hfsprogs
    state: latest 
    update_cache: yes

- name: Copy the Netatalk config
  template:
    src: afp.conf
    dest: /etc/netatalk
  register: netatalk_config

- name: Make sure the Netatalk service is running and enabled
  service: 
    name: netatalk 
    state: started 
    enabled: yes

- name: Restart Netatalk
  service:
    name: netatalk
    state: restarted
  when: netatalk_config.changed