---
- name: Make sure the MariaDB container is created and running
  docker_container:
    name: "nextcloud-mariadb"
    image: "mariadb:latest"
    pull: yes
    command: "--transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed"
    state: 'started'
    env:
      "TZ": "{{ timezone }}"
      "MYSQL_ROOT_PASSWORD": "{{ mysql_root_password }}"
      "MYSQL_DATABASE": "{{ mysql_db }}"
      "MYSQL_USER": "{{ mysql_user }}"
      "MYSQL_PASSWORD": "{{ mysql_password }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/mariadb/mysql:/var/lib/mysql"
    restart_policy: unless-stopped
    
- name: Make sure the Redis container is created and running
  docker_container:
    name: "nextcloud-redis"
    image: "redis:alpine"
    pull: yes
    state: 'started'
    restart_policy: unless-stopped
 
- name: Make sure the Nextcloud container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/linuxserver/nextcloud:php8"
    pull: yes
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/config:/config"
      - "{{ mergerfs_root }}/Nextcloud:/data"
    restart_policy: unless-stopped

- name: Add {{ container_name }} to the SWAG network (reverse-proxy)
  docker_network:
    name: swag_network
    connected:
      - "{{ container_name }}"
      - nextcloud-mariadb
      - nextcloud-redis
    appends: yes
  when: enable_swag