---
- hosts: all
  gather_facts: no

  pre_tasks:
    - import_tasks: tasks/ssh_juggle_port.yml
      tags:
        - port

    - import_tasks: tasks/user.yml
      tags:
        - user
  
- hosts: all
  become: yes

  pre_tasks:
    - name: Copy persistent data to the server
      import_tasks: tasks/copy_persistent_data.yml
      tags: containers

    - name: Remove snap functionality
      import_tasks: tasks/yeet_snaps.yml
      tags: nosnaps

  roles:
    - role: filesystems/mounts
      tags:
        - mounts

    - role: oefenweb.dns
      tags:
        - dns 

    - role: essential
      tags: 
        - essential

    # MSMTP (for SMART notifications)
    - role: chriswayg.msmtp-mailer
      tags: 
        - msmtp

    - role: docker
      tags: 
        - docker

    - role: filesystems/mergerfs
      tags:
      - mergerfs

    - role: ironicbadger.ansible_role_snapraid
      tags:
      - snapraid

    - role: filesystems/hd-idle
      tags:
      - hd-idle
      
    # SMART error checking
    - role: stuvusit.smartd
      tags:
      - smartd

    - role: avahi
      tags: 
        - avahi

    - role: containers/watchtower
      tags:
        - watchtower
        - containers

    - role: containers/unifi
      tags:
        - unifi
        - containers
      when: enable_unifi | default(False)

    - role: containers/authelia
      tags:
        - authelia
        - containers
      when: enable_authelia | default(False)

    - role: containers/swag
      tags: 
        - swag
        - containers
      when: enable_swag | default(False)

    - role: containers/bitwarden
      tags:
        - bitwarden
        - containers
      when: enable_bitwarden | default(False)
    
    - role: containers/deluge
      tags: 
        - deluge
        - containers
      when: enable_deluge | default(False)

    - role: homer
      tags: 
        - homer
        - containers
      when: enable_homer | default(False)

    - role: containers/duckdns
      tags: 
        - duckdns
        - containers
      when: enable_duckdns | default(False)

    - role: containers/nextcloud
      tags: 
        - nextcloud
        - containers
      when: enable_nextcloud | default(False)

    - role: containers/jackett
      tags: 
        - jackett
        - containers
      when: enable_jackett | default(False)

    - role: containers/sonarr
      tags: 
        - sonarr
        - containers
      when: enable_sonarr | default(False)

    - role: containers/radarr
      tags: 
        - radarr
        - containers
      when: enable_radarr | default(False)

    - role: containers/plex
      tags: 
        - plex
        - containers
      when: enable_plex | default(False)

    - role: containers/jellyfin
      tags: 
        - jellyfin
        - containers
      when: enable_jellyfin | default(False)

    - role: containers/photoprism
      tags: 
        - photoprism
        - containers
      when: enable_photoprism | default(False)


    - role: containers/wireguard
      tags: 
        - wireguard
        - containers
      when: enable_wireguard | default(False)

    - role: containers/ikev2
      tags: 
        - ikev2
        - containers
      when: enable_ikev2 | default(False)

    - role: containers/homeassistant
      tags: 
        - homeassistant
        - smarthome
        - containers
      when: enable_homeassistant | default(False)

    - role: containers/deconz
      tags: 
        - deconz
        - smarthome
        - containers
      when: enable_deconz | default(False)

    # SSH security (at the end because it breaks SSH connection)
    - role: geerlingguy.security
      tags: 
        - security
          
    # Samba
    - role: bertvv.samba
      tags: 
        - samba

    # NTP
    - role: geerlingguy.ntp
      tags: 
        - ntp
