- name: mount drives
  mount:
    name: "{{ item.name }}"
    src: "{{ item.src }}"
    fstype: xfs
    state: mounted
  with_items: "{{ disks }}"

- name: mount mergerfs array
  mount:
    name: "{{ mergerfs_root }}"
    src: /mnt/data*
    opts: direct_io,defaults,allow_other,minfreespace=50G,fsname=mergerfs
    fstype: fuse.mergerfs
    state: mounted