---
docker_deps:
  - 'apt-transport-https'
  - 'ca-certificates'
  - 'curl'
  - 'software-properties-common'
  - 'python3-pip'
  - 'virtualenv'
  - 'python3-setuptools'
  - 'python3-pip'
  - 'docker-compose'

docker_packages:
  - 'docker-ce'
  - 'docker-compose'