- name: Check if the persistent data folder exists on the remote machine
  stat:
    path: "{{ docker_dir }}"
  register: persistent_data_remote

- name: Get running containers
  docker_host_info:
    containers: yes
  register: docker_info

- name: Stop running containers
  docker_container:
    name: "{{ item }}"
    state: stopped
  loop: "{{ docker_info.containers | map(attribute='Id') | list }}"

- name: Sync the persistent docker data from the server 
  synchronize:
    mode: pull
    delete: yes
    src: "{{ docker_dir }}/"
    dest: "files/docker_persistent_data/"
  when: persistent_data_remote.stat.exists == true

- name: Start all containers
  docker_container:
    name: "{{ item }}"
    state: started
  loop: "{{ docker_info.containers | map(attribute='Id') | list }}"

