- name: Check if the persistent data folder exists on the local machine
  become: false
  local_action:
    module: stat
    path: "files/docker_persistent_data/"
  register: persistent_data_local

- name: Check if the persistent data folder exists on the remote machine
  stat:
    path: "{{ docker_dir }}"
  register: persistent_data_remote

- name: Create the persistent data folder on the remote machine
  file:
    dest: "{{ docker_dir }}"
    state: directory
    owner: notthebee
    group: notthebee
    recurse: yes
  when: persistent_data_remote.stat.exists == false

- name: Sync the persistent docker data to the server 
  synchronize:
    mode: push
    delete: yes
    src: "files/docker_persistent_data/"
    dest: "{{ docker_dir }}/"
  when: copy_persistent_data and (persistent_data_local.stat.exists == true and persistent_data_remote.stat.exists == false) or force_copy_persistent_data