- name: Check if the persistent data folder exists
  stat:
    path: "{{ docker_dir }}/{{ container_name }}/"
  register: persistent_data

- name: Sync the persistent docker data TO the server (if it doesn't already exist)
  synchronize:
    mode: push
    src: "files/docker_persistent_data/{{ container_name }}/"
    dest: "{{ docker_dir }}/{{ container_name }}/"
  when: persistent_data.stat.exists == false

- name: Sync the persistent docker data FROM the server (if it already exists)
  synchronize:
    mode: pull
    src: "{{ docker_dir }}/{{ container_name }}/"
    dest: "files/docker_persistent_data/{{ container_name }}/"
  when: persistent_data.stat.exists == true