---
- hosts: all
  gather_facts: no

  pre_tasks:
    - import_tasks: tasks/ssh_juggle_port.yml
      tags:
        - port

    - import_tasks: tasks/user.yml

  
- hosts: all
  become: yes

  roles:
    - role: essential
      tags: 
        - essential

    - role: docker
      tags: 
        - docker

    - role: bitwarden
      tags:
        - bitwarden
        - containers
    
    - role: deluge
      tags: 
        - deluge
        - containers
    
    - role: homer
      tags: 
        - homer
        - containers

    - role: duckdns
      tags: 
        - duckdns
        - containers

    - role: nextcloud
      tags: 
        - nextcloud
        - containers


    - role: swag
      tags: 
        - swag
        - containers

    # SSH security (at the end because it breaks SSH connection)
    - role: geerlingguy.security
      tags: 
        - security
