---
- hosts: all
  gather_facts: no

  pre_tasks:
    - import_tasks: tasks/ssh_juggle_port.yml
      tags:
        - port

    - import_tasks: tasks/user.yml
  
- hosts: all
  become: yes

  pre_tasks:
    - name: Copy persistent data to the server
      import_tasks: tasks/copy_persistent_data.yml
      tags: containers

  roles:
    - role: essential
      tags: 
        - essential

    # MSMTP (for SMART notifications)
    - role: chriswayg.msmtp-mailer
      tags: 
        - msmtp

    - role: docker
      tags: 
        - docker

    - role: filesystems/mergerfs
      tags:
      - mergerfs

    - role: filesystems/snapraid
      tags:
      - snapraid

    - role: filesystems/hdparm
      tags:
      - hdparm
      
    # SMART error checking
    - role: stuvusit.smartd
      tags:
      - smartd

    - role: avahi
      tags: 
        - avahi

    - role: filesystems/timemachine
      tags:
        - timemachine
      when: enable_timemachine | default(False)

    - role: containers/watchtower
      tags:
        - watchtower
        - containers

    - role: containers/swag
      tags: 
        - swag
        - containers
      when: enable_swag | default(False)

    - role: containers/bitwarden
      tags:
        - bitwarden
        - containers
      when: enable_bitwarden | default(False)
    
    - role: containers/deluge
      tags: 
        - deluge
        - containers
      when: enable_deluge | default(False)

    - role: containers/homer
      tags: 
        - homer
        - containers
      when: enable_homer | default(False)

    - role: containers/duckdns
      tags: 
        - duckdns
        - containers
      when: enable_duckdns | default(False)

    - role: containers/nextcloud
      tags: 
        - nextcloud
        - containers
      when: enable_nextcloud | default(False)

    - role: containers/jackett
      tags: 
        - jackett
        - containers
      when: enable_downloaders | default(False)

    - role: containers/sonarr
      tags: 
        - sonarr
        - containers
      when: enable_downloaders | default(False)

    - role: containers/radarr
      tags: 
        - radarr
        - containers
      when: enable_deluge | default(False)

    - role: containers/plex
      tags: 
        - plex
        - containers
      when: enable_plex | default(False)

    - role: containers/wireguard
      tags: 
        - wireguard
        - containers
      when: enable_wireguard | default(False)

    - role: containers/home-assistant
      tags: 
        - home-assistant
        - smarthome
        - containers
      when: enable_smarthome | default(False)

    - role: containers/deconz
      tags: 
        - deconz
        - smarthome
        - containers
      when: enable_smarthome | default(False)


    # SSH security (at the end because it breaks SSH connection)
    - role: geerlingguy.security
      tags: 
        - security
          
    # Samba
    - role: bertvv.samba
      tags: 
        - samba

    # NTP
    - role: geerlingguy.ntp
      tags: 
        - ntp
