---
- hosts: centralia
  gather_facts: no

  pre_tasks:
    - import_tasks: tasks/ssh_juggle_port.yml
      tags:
        - port

    - import_tasks: tasks/user.yml

  
- hosts: all
  become: yes

  roles:
    - role: essential
      tags: 
        - essential

    - role: docker
      tags: 
        - docker
    
    - role: watchtower
      tags:
        - watchtower
        - containers

    - role: bitwarden
      tags:
        - bitwarden
        - containers
    
    - role: deluge
      tags: 
        - deluge
        - containers
    
    - role: homer
      tags: 
        - homer
        - containers

    - role: duckdns
      tags: 
        - duckdns
        - containers

    - role: nextcloud
      tags: 
        - nextcloud
        - containers

    - role: jackett
      tags: 
        - jackett
        - containers

    - role: sonarr
      tags: 
        - sonarr
        - containers

    - role: radarr
      tags: 
        - radarr
        - containers

    - role: plex
      tags: 
        - plex
        - containers

    - role: swag
      tags: 
        - swag
        - containers

    - role: wireguard
      tags: 
        - wireguard
        - containers

    # SSH security (at the end because it breaks SSH connection)
    - role: geerlingguy.security
      tags: 
        - security

    # NTP
    - role: geerlingguy.ntp
      tags: 
        - ntp
