---
- hosts: all
  gather_facts: no

  pre_tasks:
    - import_tasks: tasks/ssh_juggle_port.yml

    - import_tasks: tasks/user.yml

  
- hosts: all
  become: yes

  roles:
    - role: essential

    - role: docker

    # SSH security (at the end because it breaks SSH connection)
    - role: geerlingguy.security