---
- hosts: all
  gather_facts: no

  pre_tasks:
    - import_tasks: tasks/ssh_juggle_port.yml
      tags: 'port'

    - import_tasks: tasks/user.yml

  
- hosts: all
  become: yes

  roles:
    - role: essential
      tags: 'essential'

    - role: docker
      tags: 'docker'

    - role: bitwarden
      tags: 'bitwarden'
    
    - role: deluge
      tags: 'deluge'
    
    - role: homer
      tags: 'homer'

    # SSH security (at the end because it breaks SSH connection)
    - role: geerlingguy.security
      tags: 'security'
