---
- name: Install required system packages
  apt: 
    name:
      - 'apt-transport-https'
      - 'ca-certificates'
      - 'curl'
      - 'software-properties-common'
      - 'python3-pip'
      - 'virtualenv'
      - 'python3-setuptools'
    state: latest 
    update_cache: yes

- name: Ensure group docker exists
  group:
    name: docker
    state: present

- name: Add user "{{ username }}" to group docker
  user:
    name: '{{ username }}'
    groups: 
      - docker
    append: yes

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Update apt and install docker-ce
  apt: 
    update_cache: yes 
    name: docker-ce 
    state: latest

- name: Make sure Docker is running and enabled
  service: 
    name: docker 
    state: started 
    enabled: yes

- name: Check if the persistent data folder exists on the remote machine
  stat:
    path: "{{ docker_dir }}"
  register: persistent_data

- name: Check if the persistent data folder is empty
  find:
    paths: 
      - "{{ docker_dir }}/"
    recurse: yes
  register: persistent_data_find

- name: Create the persistent data folder on the remote machine
  file:
    dest: "{{ docker_dir }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: yes
  when: persistent_data.stat.exists == false

- name: Restore the "{{ docker_dir }}" folder from the MergerFS array
  shell:
    cmd: "rsync -avz --delete {{ mergerfs_root }}/docker_data {{ docker_dir }}"
  when: persistent_data_find.matched < 20 or persistent_data.stat.exists == false