---
- import_tasks: tasks/persistent_data.yml


- name: Make sure the SWAG container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/linuxserver/swag"
    pull: yes
    capabilities: 
      - net_admin
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "URL": "{{ host }}"
      "SUBDOMAINS": "wildcard"
      "DUCKDNSTOKEN": "{{ duckdns_token }}"
      "VALIDATION": "duckdns"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/config:/config"
    restart_policy: unless-stopped


- name: Create a SWAG network, add all the containers to be reverse-proxied into it
  docker_network:
    name: swag_network
    connected:
      - swag
      - nextcloud
      - mariadb
      - bitwarden